# Generated by Django 5.1.6 on 2025-04-24 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_name'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friend_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stepstracking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps_tracking', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='userachievementprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_progress', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='userdailyquest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quests', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='userfriend',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='userfriend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_friends', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='userworkoutschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_schedules', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workout_plans', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='authentication.user'),
        ),
    ]
