# Generated by Django 5.1.6 on 2025-04-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_stepstracking_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='uid',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friend_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
