# Generated by Django 5.1.6 on 2025-04-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_userprofile_uid_alter_userprofile_friend_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_height',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='goal_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='method',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_icon/'),
        ),
    ]
